export { default as App } from 'pages/App';
export { default as Home } from 'pages/Home';
export { default as Vote} from 'pages/Vote';
export { default as Dashboard } from 'pages/Dashboard';
export { default as Telemetry } from 'pages/Telemetry';
export { default as UserPage } from 'pages/UserPage';
export { default as Settings } from 'pages/Settings';
export { default as LoginOrRegister } from 'pages/LoginOrRegister';
export { default as About } from 'pages/About';
export { default as Tasks } from 'pages/Tasks';
export { default as UiPage } from 'pages/UiPage';
export { default as Guide } from 'pages/Guide';
